---

- name: Copy telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/opt/telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify:
    - restart telegraf
